title: GitHub Pages LP Template
description: Reusable GitHub Pages + Jekyll landing page template.
lang: ja
url: "https://ugnoguchigxp.github.io"
baseurl: "/github-pages"

source: site
destination: docs

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: default

include:
  - .nojekyll

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
